#!/usr/bin/env bash

# use if you need
# warning: kills all sessions
if $(tmux has-session 2>/dev/null); then tmux kill-session; fi

# if $(tmux has-session 2>/dev/null); then tmux -2u att; exit; fi

tmux new-session -d -n bash -s 0 -c "/home/homk/prg/geo/kloud-records/Kloud.Records.Local.Web/"
sleep 0.2

tmux split-window -t 0:0.0 -v
tmux split-window -t 0:0.0 -h
tmux split-window -t 0:0.0 -v
tmux split-window -t 0:0.2 -v

# 0 | 2
# - | -
# 1 | 3
# - - -
#   4

tmux send-keys -t 0:0.0 "cd /home/homk/prg/geo/kloud-records/Kloud.Records.Local.Web/" Enter
tmux send-keys -t 0:0.1 "cd /home/homk/prg/geo/kloud-records/Kloud.Records.Local.Web/" Enter
tmux send-keys -t 0:0.2 "cd /home/homk/prg/geo/kloud-records/Kloud.Records.Local.Web/" Enter
tmux send-keys -t 0:0.3 "cd /home/homk/prg/geo/kloud-records/Kloud.Records.Local.Web/" Enter
tmux send-keys -t 0:0.4 "cd /home/homk/prg/geo/kloud-records/Kloud.Records.Local.Web/" Enter

tmux send-keys -t 0:0.0 "npm run watch-records-core"
tmux send-keys -t 0:0.1 "npm run watch-records-utils"
tmux send-keys -t 0:0.2 "npm run watch-records-visuals"
tmux send-keys -t 0:0.3 "npm run watch-records"
tmux send-keys -t 0:0.4 "npm run start"

tmux set -g pane-border-format "#{pane_index} #{pane_current_command}"

tmux select-pane -t 0:0.0

sleep 0.2
tmux -2u att
